---
title: "Fiscal Gap Analysis"
author: "Finances of the Nation"
output: html_document
runtime: shiny
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE)
library(tidyverse)
library(scales)
library(ggthemes)
library(shiny)
library(shinyWidgets)
library(RColorBrewer)
library(png)
library(gridExtra)
library(grid)
```

Text description here. Link to a [Website](http://financesofthenation.ca).

```{r load data}
# Loads the data
data<-read.csv("FiscalGapScenarios.csv")
```

```{r run app}
# Define the "inputs" (the selectors, titles, etc.)
ui<-fluidPage(
  titlePanel('Visualization of Fiscal Gap Analysis'),
  helpText("Based on estimates from Tombe (2020, Canadian Tax Journal)"),
  fluidRow(
    sidebarPanel(
    sliderInput('rate','Provincial Interest Rate (%)*',min=min(data$r)*100,max=max(data$r)*100,value=4,step=0.5),
    sliderInput('health_inflation', 'Health-Specific Inflation (%)',min=min(data$health_inflation)*100,max=max(data$health_inflation)*100,value=1,step=0.25),
    sliderInput('labour_prod', 'Labour Productivity Growth (%)', min=min(data$labour_prod)*100,max=max(data$labour_prod)*100,value=1,step=0.25),
    selectInput('years', 'Time Horizon (Years)', unique(data$years),selected="75"),
    selectInput('pop_scenario', 'Population Scenario', unique(data$pop_scenario)),
    hr(),
    helpText("* Federal borrowing rates are always 1 percentage points lower than provincial.")
  ),
  mainPanel(
    tabsetPanel(
      tabPanel("Plot",plotOutput('plot1',height=425,width=650)),
      tabPanel("Table",tableOutput("table"))
    ),
    hr(),
    helpText("Note here."),
  ),
)
)

# Define the interactive "server" environment
server<-function(input, output) {

  # Combine the selected variables into a new data frame
  selectedData <- reactive({
    data %>% filter(r %in% unique(input$rate/100),
                    health_inflation %in% unique(input$health_inflation/100),
                    labour_prod %in% unique(input$labour_prod/100),
                    years %in% unique(input$years),
                    pop_scenario %in% unique(input$pop_scenario)) %>%
      mutate(short=factor(short,levels=c('BC','AB','SK','MB','ON','QC','NB','NS','PE','NL','PROV','FED')))
  })
  
  # Load the FON logo
  img <- readPNG("FON_logo.png") 
  logo <- rasterGrob(img) 

  # Generate the Plot
  output$plot1 <- renderPlot({
    g1<-ggplot(selectedData(),aes(short,same_netdebt))+
            geom_col(fill='dodgerblue3')+
            geom_hline(yintercept=0,size=1)+
            theme_minimal()+
            scale_fill_brewer(name="",palette="Set1")+
            theme(panel.grid.minor = element_blank(),
            axis.title.y = element_text(size=10),
            axis.title.x = element_text(size=10),
            axis.text.y = element_text(size=10),
            legend.position="top",
            axis.text.x = element_text(size=10),
            plot.title = element_text(face = "bold",size=14),
            plot.subtitle = element_text(size = 10, color = "gray40"),
            plot.caption = element_text(size = 8, color = "gray40",hjust=1),
            panel.grid.major.x = element_blank())+
            scale_y_continuous(label=percent)+
            labs(x="",y="Share of GDP per Year",
                 title="Long-Run Fiscal Gaps in Canada",
                 subtitle="Source: Estimates from Tombe (2020, CTJ)",
                 caption="Displays the hypothetical fiscal adjustment required for
sustainable debt over a 75-year horizon, with and without EQ.")
    
    # Add the logo to the plot
    g2 <- ggplot(mapping = aes(x = 0:1, y = 0)) +
            theme_void() +
            annotation_custom(logo, xmin = 0, xmax = .4)
    
    # Combine the plot and the logo
    gridExtra::grid.arrange(g1, g2, heights = c(.9, .1))
  },res=100)
  
  # Generate a summary table of the data underlying the figure
  output$table <- renderTable({
    selectedData() %>%
      mutate(same_netdebt=100*same_netdebt) %>%
      select(Province=short,
             `Fiscal Gap`=same_netdebt)
  })

}
shinyApp(ui, server, options = list(height = 800,width=1100))
```

